GROUPS = [
    "GENERAL",
    "WRITING",
    "APPLICATION FRAMEWORK",
    "TKINTER APPS",
    "M1",
    "ARCHITECTURE",
]


DOCUMENTS = [
    {
        "group": "GENERAL",
        "key": "general-background",
        "label": "General background",
        "document-id": "lions_dictionary_for_llms",
        "selected": False,
        "designation": "required",
        "reason": "Read this for high-level orientation to Lion's recurring concepts, systems, and vocabulary.",
    },
    {
        "group": "GENERAL",
        "key": "general-background-abbreviated",
        "label": "General background (abbreviated)",
        "document-id": "lions_dictionary_for_llms.abbreviated.v1",
        "selected": False,
        "designation": "required",
        "reason": "Read this for an abbreviated high-level orientation to Lion's recurring concepts, systems, and vocabulary.",
    },
    {
        "group": "GENERAL",
        "key": "project-directory-system",
        "label": "Lion's project directory system",
        "document-id": "",
        "selected": True,
        "designation": "required",
        "reason": "Read this for a brief overview of how Lion's projects and repositories are organized.",
    },
    {
        "group": "GENERAL",
        "key": "programming-guidelines",
        "label": "Programming guidelines",
        "document-id": "lionsphilosophyofprogramming.2025.simplified",
        "selected": True,
        "designation": "required",
        "reason": "These are the programming guidelines that you shall implement the program with.",
    },
    {
        "group": "WRITING",
        "key": "json-document-writing",
        "label": "JSON documentation-writing guide",
        "document-id": "lions-docs.description.json-document-format-for-llms.v1",
        "selected": False,
        "designation": "recommended",
        "reason": "Read this when writing JSON documents intended for Lion's systems or for LLM consumption.",
    },
    {
        "group": "WRITING",
        "key": "json-document-writing-minimal",
        "label": "JSON documentation-writing guide (minimal)",
        "document-id": "lions-docs.description.json-document-format-for-llms.minimal.v1",
        "selected": True,
        "designation": "recommended",
        "reason": "A condensed version of the JSON documentation-writing guide; read this for the essentials when the full guide is more than you need.",
    },
    {
        "group": "WRITING",
        "key": "softspec",
        "label": "SoftSpec v2",
        "document-id": "softspec.spec.v2",
        "selected": False,
        "designation": "recommended",
        "reason": "Read this when specifying data structures in JSON documents; SoftSpec is the preferred approach.",
    },
    {
        "group": "WRITING",
        "key": "softspec-v3",
        "label": "SoftSpec v3",
        "document-id": "softspec.spec.v3",
        "selected": True,
        "designation": "recommended",
        "reason": "Read this when specifying data structures in JSON documents; SoftSpec is the preferred approach. (v3 fixes minor errors in v2, includes 'json_clean', and describes how to incorporate data-dictionary entries.)",
    },
    {
        "group": "APPLICATION FRAMEWORK",
        "key": "lionscliapp",
        "label": "lionscliapp reference",
        "document-id": "lionscliapp.reference.v1",
        "selected": False,
        "designation": "required",
        "reason": "The program you are implementing will be built with the lionscliapp framework. Read this so that you know how to use it.",
    },
    {
        "group": "APPLICATION FRAMEWORK",
        "key": "machine-root",
        "label": "Machine Root package",
        "document-id": "machine-root.package.description.v1",
        "selected": False,
        "designation": "required",
        "reason": "Read this when the application needs to resolve named machine-local resources through Machine Root.",
    },
    {
        "group": "TKINTER APPS",
        "key": "tkinter-conventions",
        "label": "Conventions for tkinter applications",
        "document-id": "lions-tkinter-development-conventions.v1",
        "selected": False,
        "designation": "required",
        "reason": "When you write tkinter user interfaces, follow these guidelines.",
    },
    {
        "group": "TKINTER APPS",
        "key": "tkintertester-reference",
        "label": "tkintertester Reference",
        "document-id": "tkintertester.reference",
        "selected": False,
        "designation": "required",
        "reason": "When you write Tkinter GUI tests, use tkintertester. Read this so that you understand the harness, its event-loop-native test model, and its rules.",
    },
    {
        "group": "TKINTER APPS",
        "key": "tkintertester-lionscliapp",
        "label": "tkintertester with lionscliapp",
        "document-id": "tkintertester.with_lionscliapp.spec.v0.1",
        "selected": False,
        "designation": "required",
        "reason": "When you combine tkintertester with lionscliapp, follow this integration pattern so the CLI lifecycle and Tk test lifecycle stay correctly separated.",
    },
    {
        "group": "TKINTER APPS",
        "key": "tkvillage-manual-v1",
        "label": "TkVillage System Manual",
        "document-id": "tkvillage.system-manual.v1",
        "selected": False,
        "designation": "required",
        "reason": "Explains how to use TkVillage, a lightweight procedural Tkinter host runtime.",
    },
    {
        "group": "TKINTER APPS",
        "key": "tkvillage-api-v1",
        "label": "TkVillage System API Reference",
        "document-id": "tkvillage.system-api-reference.v1",
        "selected": False,
        "designation": "required",
        "reason": "Provide a full user-facing API reference for the current TkVillage kernel.",
    },
    {
        "group": "TKINTER APPS",
        "key": "tkvillage-data-dictionary-v1",
        "label": "TkVillage app.py Data Dictionary",
        "document-id": "tkvillage.data-dictionary.app.v1",
        "selected": False,
        "designation": "recommended",
        "reason": "Document the runtime data owned by src/tkvillage/app.py using SoftSpec v3, including structural schemas and data-dictionary annotations for runtime ownership, lifecycle, reset behavior, and serialization boundaries.",
    },
    {
        "group": "M1",
        "key": "m1-core",
        "label": "M1 Lattice core specification",
        "document-id": "m1lattice.spec.core.v2",
        "selected": False,
        "designation": "required",
        "reason": "You are going to be handling M1 data. Read this so that you understand the core structure and behavior of M1 entities and aspects.",
    },
    {
        "group": "M1",
        "key": "m1-transport",
        "label": "M1 Lattice transport specification",
        "document-id": "m1lattice.spec.transport.v2",
        "selected": False,
        "designation": "required",
        "reason": "You are going to be storing or exchanging M1 data. Read this so that you understand its transport representation.",
    },
    {
        "group": "M1",
        "key": "m1-link-types",
        "label": "M1 recommended link types",
        "document-id": "m1lattice.vocab.linktypes.v1",
        "selected": False,
        "designation": "required",
        "reason": "Read this when choosing link types for relationships in M1 data.",
    },
    {
        "group": "M1",
        "key": "m1-merging",
        "label": "M1 merging guide",
        "document-id": "m1lattice.merging.guide.v2",
        "selected": False,
        "designation": "required",
        "reason": "Read this when combining M1 transport units or reasoning about merge behavior.",
    },
    {
        "group": "M1",
        "key": "m1-runtime",
        "label": "M1 runtime manual",
        "document-id": "m1lattice.runtime-manual",
        "selected": False,
        "designation": "required",
        "reason": "Read this so that you know how to use the M1 runtime.",
    },
    {
        "group": "ARCHITECTURE",
        "key": "reducer-core-architecture",
        "label": "Reducer-Core Architecture",
        "document-id": "",
        "selected": False,
        "designation": "required",
        "reason": "The program will use the Reducer-Core Architecture. Read this to understand the architecture and its specific terms of use.",
    },
    {
        "group": "ARCHITECTURE",
        "key": "cira",
        "label": "CIRA Agentic Implementation Brief",
        "document-id": "cira.agentic-implementation-brief.v1",
        "selected": False,
        "designation": "required",
        "reason": "The program is likely to use, or may be required to use, the Coordinated Interactive Runtime Architecture (CIRA). Read this so that you know how to implement it.",
    },
]


def new_data():
    return {
        "purpose": "",
        "options": {
            "encourage-questions": False,
            "request-ack": True,
        },
        "documents": {
            item["key"]: {
                "selected": item["selected"],
                "designation": item["designation"],
                "reason": item["reason"],
            }
            for item in DOCUMENTS
        },
    }
